-- QUANTIDADE DE PRODUTO VENDIDO POR UNIDADE
SELECT DMV.C6_PRODUTO, DMV.C6_SEGUM, DMV.C6_DESCRI, SUM(DMV.C6_QTDVEN)/CAST((CASE WHEN TABPROD.B1_PESO = 0 THEN 1 ELSE TABPROD.B1_PESO END) AS DECIMAL) QTDUNI
FROM DATA_MART_VENDAS DMV
INNER JOIN SF4010 TES ON TES.F4_COD_PK = DMV.F4_COD_PK AND TES.F4_DUPLIC = 'S' AND TES.D_E_L_E_T_ = ''
INNER JOIN SB1010 TABPROD ON TABPROD.B1_COD_PK = DMV.B1_COD_PK AND TABPROD.B1_FILIAL = '01' AND TABPROD.D_E_L_E_T_ = ''
WHERE  DMV.C5_FILIAL = '01' AND DMV.C5_FECENT = '20181108' --AND PED.D_E_L_E_T_ ='' 
AND DMV.C6_PRODUTO < '800' AND DMV.C5_TIPO = 'N'
GROUP BY DMV.C5_FECENT,DMV.C6_PRODUTO,DMV.C6_SEGUM, DMV.C6_DESCRI, TABPROD.B1_PESO
ORDER BY DMV.C5_FECENT,DMV.C6_PRODUTO

-- QUANTIDADE DE PRODUTO VENDIDO POR VENDEDOR EM KG
SELECT  VEND.A3_NOME, SUM(DMV.C6_QTDVEN) AS SOMA
FROM DATA_MART_VENDAS DMV
INNER JOIN SF4010 TES ON TES.F4_COD_PK = DMV.F4_COD_PK AND TES.F4_DUPLIC = 'S' AND TES.D_E_L_E_T_ = ''
INNER JOIN SA3010 VEND ON VEND.A3_COD_PK = DMV.A3_COD_PK AND VEND.D_E_L_E_T_ = ''
WHERE DMV.C5_FILIAL = '01' AND DMV.C5_FECENT = '20181108' AND DMV.C5_TIPO = 'N'
GROUP BY VEND.A3_NOME
ORDER BY VEND.A3_NOME

-- QUANTIDADE DE PRODUTO VENDIDO POR CIDADE EM KG 
SELECT ROTA.DA6_REF, ROTA.DA6_ROTA ,SUM(DMV.C6_QTDVEN) AS SOMA
FROM DATA_MART_VENDAS DMV
INNER JOIN DA7010 CID ON CID.DA7_COD_PK = DMV.DA7_COD_PK AND CID.D_E_L_E_T_ = ''
INNER JOIN DA6010 ROTA ON ROTA.DA6_COD_PK = DMV.DA6_COD_PK AND ROTA.D_E_L_E_T_ = ''
INNER JOIN SF4010 TES ON TES.F4_COD_PK = DMV.F4_COD_PK AND TES.F4_DUPLIC = 'S' AND TES.D_E_L_E_T_ = ''
WHERE  DMV.C5_FILIAL = '01' AND DMV.C5_FECENT = '20181108'   AND DMV.C5_TIPO = 'N'
GROUP BY ROTA.DA6_REF, ROTA.DA6_ROTA 
ORDER BY ROTA.DA6_REF

--FATURAMENTO

-- QUANTIDADE DE FATURAMENTO POR CIDADE 
SELECT  ROTA.DA6_REF, ROTA.DA6_ROTA,sum(DMF.D2_QUANT) AS SOMA, SUM(DMF.D2_TOTAL) AS FATURAMENTO
FROM DATA_MART_FATURAMENTO DMF
INNER JOIN SF4010 TES ON TES.F4_COD_PK = DMF.F4_COD_PK AND TES.F4_DUPLIC = 'S' AND TES.D_E_L_E_T_ = ''
INNER JOIN DA7010 CID ON CID.DA7_COD_PK = DMF.DA7_COD_PK AND CID.D_E_L_E_T_ = ''
INNER JOIN DA6010 ROTA ON ROTA.DA6_COD_PK = DMF.DA6_COD_PK AND ROTA.D_E_L_E_T_ = ''
WHERE DMF.D2_FILIAL = '01' AND DMF.D2_EMISSAO = '20181108' AND DMF.F2_TIPO = 'N'
GROUP BY ROTA.DA6_REF, ROTA.DA6_ROTA
ORDER BY ROTA.DA6_REF


-- QUANTIDADE DE FATURAMENTO POR VENDEDOR
SELECT VEND.A3_NOME,sum(DMF.D2_QUANT) AS SOMA, SUM(DMF.D2_TOTAL) AS FATURAMENTO
FROM DATA_MART_FATURAMENTO DMF
INNER JOIN SF4010 TES ON DMF.F4_COD_PK = TES.F4_COD_PK AND TES.F4_DUPLIC = 'S' AND TES.D_E_L_E_T_ = ''
INNER JOIN SA3010 VEND ON VEND.A3_COD_PK = DMF.A3_COD_PK AND VEND.D_E_L_E_T_ = ''
WHERE DMF.D2_FILIAL = '01' AND DMF.D2_EMISSAO = '20181108' AND DMF.F2_TIPO = 'N'
GROUP BY VEND.A3_NOME
ORDER BY VEND.A3_NOME


-- QUANTIDADE DE FATURAMENTO POR PRODUTO
SELECT TABPROD.B1_DESC,sum(DMF.D2_QUANT) AS SOMA, SUM(DMF.D2_TOTAL) AS FATURAMENTO
FROM DATA_MART_FATURAMENTO DMF
INNER JOIN SF4010 TES ON DMF.F4_COD_PK = TES.F4_COD_PK AND TES.F4_DUPLIC = 'S' AND TES.D_E_L_E_T_ = ''
INNER JOIN SB1010 TABPROD ON DMF.B1_COD_PK = TABPROD.B1_COD_PK AND TABPROD.D_E_L_E_T_ = ''
WHERE DMF.D2_FILIAL = '01' AND DMF.D2_EMISSAO = '20181108' AND DMF.F2_TIPO = 'N'
GROUP BY TABPROD.B1_DESC
ORDER BY TABPROD.B1_DESC
