CREATE DATABASE DATA_WAREHOUSE
GO

USE DATA_WAREHOUSE
GO

--cubo de dados vendas
CREATE TABLE DATA_MART_VENDAS(
	DM_VENDAS_COD_PK INTEGER IDENTITY,
	--C5_COD_PK INTEGER, --FK SC5010
	--C6_COD_PK INTEGER, --FK SC6010
	B1_COD_PK INTEGER, --FK SB1010
	A3_COD_PK INTEGER, --FK SA3010
	DA6_COD_PK INTEGER, --FK DA6010
	DA7_COD_PK INTEGER, --FK DA7010
	F4_COD_PK INTEGER, --FK SF4010
	C5_FECENT VARCHAR(8) NOT NULL,
	C5_NUM VARCHAR(6) NOT NULL,
	C5_VEND1 VARCHAR(6) NOT NULL,
	C5_CLIENT VARCHAR(11) NOT NULL,
	C5_LOJAENT VARCHAR(4) NOT NULL,
	C5_FILIAL VARCHAR(2),
	C5_TIPO VARCHAR(1),
	C6_PRODUTO VARCHAR(15), 
	C6_DESCRI VARCHAR(50) NOT NULL, 
	C6_QTDVEN FLOAT NOT NULL,
	C6_NUM VARCHAR(6) NOT NULL, 
	C6_VALOR FLOAT NOT NULL,
	C6_QTDREAL FLOAT,
	C6_FILIAL VARCHAR(2),
	C6_SEGUM VARCHAR(2),
	C6_TES VARCHAR(3)
)
GO


--cubo de dados faturamento
CREATE TABLE DATA_MART_FATURAMENTO(
	DM_FATURAMENTO_COD_PK INTEGER IDENTITY,
	B1_COD_PK INTEGER, --FK SB1010
	A3_COD_PK INTEGER, --FK SA3010
	DA6_COD_PK INTEGER, --FK DA6010
	DA7_COD_PK INTEGER, --FK DA7010
	F4_COD_PK INTEGER, --FK SF4010
	F2_CLIENTE VARCHAR(11),
	F2_LOJA VARCHAR(4),
	F2_TIPO VARCHAR(1),
	F2_FILIAL VARCHAR(2),
	F2_DOC VARCHAR(9),
	F2_SERIE VARCHAR(3),
	F2_VEND1 VARCHAR(6),
	D2_SERIE VARCHAR(3),
	D2_DOC VARCHAR(9),
	D2_EMISSAO VARCHAR(8),
	D2_FILIAL VARCHAR(2),
	D2_COD VARCHAR(15),
	D2_QUANT FLOAT,
	D2_PRCVEN FLOAT,
	D2_TOTAL FLOAT,
	D2_TES VARCHAR(3),
	D2_CLIENTE VARCHAR(11),
	D2_LOJA VARCHAR(4)
)
GO

--Staging area pedido
CREATE TABLE SA_PEDIDO(
	SA_PED_COD_PK INTEGER IDENTITY,
	C5_FECENT VARCHAR(8) NOT NULL,
	C5_NUM VARCHAR(6) NOT NULL,
	C5_VEND1 VARCHAR(6) NOT NULL,
	C5_CLIENT VARCHAR(11) NOT NULL,
	C5_LOJAENT VARCHAR(4) NOT NULL,
	C5_FILIAL VARCHAR(2),
	C5_NOTA VARCHAR(9),
	C5_TIPO VARCHAR(1),
	C6_PRODUTO VARCHAR(15), 
	C6_DESCRI VARCHAR(50) NOT NULL, 
	C6_QTDVEN FLOAT NOT NULL,
	C6_NUM VARCHAR(6) NOT NULL, 
	C6_VALOR FLOAT NOT NULL,
	C6_QTDREAL FLOAT,
	C6_FILIAL VARCHAR(2),
	C6_SEGUM VARCHAR(2),
	C6_TES VARCHAR(3)
)
GO


--Staging area Faturmaneto
CREATE TABLE SA_FATURAMENTO(
	SA_FAT_COD_PK INTEGER IDENTITY,
	F2_CLIENTE VARCHAR(11),
	F2_LOJA VARCHAR(4),
	F2_TIPO VARCHAR(1),
	F2_FILIAL VARCHAR(2),
	F2_DOC VARCHAR(9),
	F2_SERIE VARCHAR(3),
	F2_VEND1 VARCHAR(6),
	D2_SERIE VARCHAR(3),
	D2_DOC VARCHAR(9),
	D2_EMISSAO VARCHAR(8),
	D2_FILIAL VARCHAR(2),
	D2_COD VARCHAR(15),
	D2_QUANT FLOAT,
	D2_PRCVEN FLOAT,
	D2_TOTAL FLOAT,
	D2_TES VARCHAR(3),
	D2_CLIENTE VARCHAR(11),
	D2_LOJA VARCHAR(4)
)
GO


CREATE TABLE SB1010 (
	B1_COD_PK INTEGER IDENTITY,
	B1_COD VARCHAR(15) NOT NULL,
	B1_DESC VARCHAR(50),
	B1_PESO FLOAT NOT NULL DEFAULT 1,
	B1_FILIAL VARCHAR(2),
	D_E_L_E_T_ VARCHAR(1)
)
GO

CREATE TABLE SA3010 (
	A3_COD_PK INTEGER IDENTITY,
	A3_COD VARCHAR(6),
	A3_NOME VARCHAR(40),
	D_E_L_E_T_ VARCHAR(1)
)
GO

CREATE TABLE DA7010(
	DA7_COD_PK INTEGER IDENTITY,
	DA7_CLIENT VARCHAR(11),
	DA7_LOJA VARCHAR(4),
	DA7_ROTA VARCHAR(6),
	D_E_L_E_T_ VARCHAR(1)
)
GO

CREATE TABLE DA6010(
	DA6_COD_PK INTEGER IDENTITY,
	DA6_REF VARCHAR(40),
	DA6_ROTA VARCHAR(6),
	D_E_L_E_T_ VARCHAR(1)
)
GO

CREATE TABLE SF4010(
	F4_COD_PK INTEGER IDENTITY,
	F4_CODIGO VARCHAR(3),
	F4_DUPLIC VARCHAR(1),
	D_E_L_E_T_ VARCHAR(1)
)
GO


-- PRIMARY KEY

ALTER TABLE DATA_MART_VENDAS ADD CONSTRAINT PK_DATA_MART_VENDAS PRIMARY KEY(DM_VENDAS_COD_PK)
ALTER TABLE DATA_MART_FATURAMENTO ADD CONSTRAINT PK_DATA_MART_FATURAMENTO PRIMARY KEY(DM_FATURAMENTO_COD_PK)
ALTER TABLE SA_PEDIDO ADD CONSTRAINT PK_SA_PEDIDO PRIMARY KEY (SA_PED_COD_PK)
ALTER TABLE SA_FATURAMENTO ADD CONSTRAINT PK_SA_FATURAMENTO PRIMARY KEY (SA_FAT_COD_PK)
ALTER TABLE SB1010 ADD CONSTRAINT PK_SB1010 PRIMARY KEY(B1_COD_PK)
ALTER TABLE SA3010 ADD CONSTRAINT PK_SA3010 PRIMARY KEY(A3_COD_PK)
ALTER TABLE DA6010 ADD CONSTRAINT PK_DA6010 PRIMARY KEY(DA6_COD_PK)
ALTER TABLE DA7010 ADD CONSTRAINT PK_DA7010 PRIMARY KEY(DA7_COD_PK)
ALTER TABLE SF4010 ADD CONSTRAINT PK_SF4010 PRIMARY KEY(F4_COD_PK)
GO

--FOREIGN KEY

ALTER TABLE DATA_MART_VENDAS ADD CONSTRAINT FK_DM_VENDAS_SB1010 FOREIGN KEY(B1_COD_PK) REFERENCES SB1010(B1_COD_PK)
ALTER TABLE DATA_MART_VENDAS ADD CONSTRAINT FK_DM_VENDAS_SA3010 FOREIGN KEY(A3_COD_PK) REFERENCES SA3010(A3_COD_PK)
ALTER TABLE DATA_MART_VENDAS ADD CONSTRAINT FK_DM_VENDAS_DA6010 FOREIGN KEY(DA6_COD_PK) REFERENCES DA6010(DA6_COD_PK)
ALTER TABLE DATA_MART_VENDAS ADD CONSTRAINT FK_DM_VENDAS_DA7010 FOREIGN KEY(DA7_COD_PK) REFERENCES DA7010(DA7_COD_PK)
ALTER TABLE DATA_MART_VENDAS ADD CONSTRAINT FK_DM_VENDAS_SF4010 FOREIGN KEY(F4_COD_PK) REFERENCES SF4010(F4_COD_PK)
GO

ALTER TABLE DATA_MART_FATURAMENTO ADD CONSTRAINT FK_DM_FATURAMENTO_SB1010 FOREIGN KEY(B1_COD_PK) REFERENCES SB1010(B1_COD_PK)
ALTER TABLE DATA_MART_FATURAMENTO ADD CONSTRAINT FK_DM_FATURAMENTO_SA3010 FOREIGN KEY(A3_COD_PK) REFERENCES SA3010(A3_COD_PK)
ALTER TABLE DATA_MART_FATURAMENTO ADD CONSTRAINT FK_DM_FATURAMENTO_DA6010 FOREIGN KEY(DA6_COD_PK) REFERENCES DA6010(DA6_COD_PK)
ALTER TABLE DATA_MART_FATURAMENTO ADD CONSTRAINT FK_DM_FATURAMENTO_DA7010 FOREIGN KEY(DA7_COD_PK) REFERENCES DA7010(DA7_COD_PK)
ALTER TABLE DATA_MART_FATURAMENTO ADD CONSTRAINT FK_DM_FATURAMENTO_SF4010 FOREIGN KEY(F4_COD_PK) REFERENCES SF4010(F4_COD_PK)
GO

