CREATE TRIGGER INSERE_SB1010
ON Protheus12_Teste.dbo.SB1010 FOR INSERT
AS
BEGIN
	DECLARE @B1_COD VARCHAR(15)
	SELECT @B1_COD = ((SELECT B1_COD FROM inserted))
	IF @B1_COD BETWEEN '100' AND '800'
		INSERT INTO DATA_WAREHOUSE.dbo.SB1010 VALUES ((SELECT B1_COD FROM inserted), 
												  (SELECT B1_DESC FROM inserted),
												  (SELECT B1_PESO FROM inserted),
												  (SELECT B1_FILIAL FROM inserted),
												  (SELECT D_E_L_E_T_ FROM inserted))
END 
GO

CREATE TRIGGER INSERE_SA3010
ON Protheus12_Teste.dbo.SA3010 FOR INSERT
AS
BEGIN
	INSERT INTO DATA_WAREHOUSE.dbo.SA3010 VALUES ((SELECT A3_COD FROM inserted), 
												  (SELECT A3_NOME FROM inserted),
												  (SELECT D_E_L_E_T_ FROM inserted))
END 
GO

CREATE TRIGGER INSERE_DA6010
ON Protheus12_Teste.dbo.DA6010 FOR INSERT
AS
BEGIN
	INSERT INTO DATA_WAREHOUSE.dbo.DA6010 VALUES ((SELECT DA6_REF FROM inserted), 
												  (SELECT DA6_ROTA FROM inserted),
												  (SELECT D_E_L_E_T_ FROM inserted))
END 
GO

CREATE TRIGGER INSERE_DA7010
ON Protheus12_Teste.dbo.DA7010 FOR INSERT
AS
BEGIN
	INSERT INTO DATA_WAREHOUSE.dbo.DA7010 VALUES ((SELECT DA7_CLIENT FROM inserted), 
												  (SELECT DA7_LOJA FROM inserted),
												  (SELECT DA7_ROTA FROM inserted),
												  (SELECT D_E_L_E_T_ FROM inserted))
END 
GO


CREATE TRIGGER INSERE_SF4010
ON Protheus12_Teste.dbo.SF4010 FOR INSERT
AS
BEGIN
	INSERT INTO DATA_WAREHOUSE.dbo.SF4010 VALUES ((SELECT F4_CODIGO FROM inserted), 
												  (SELECT F4_DUPLIC FROM inserted),
												  (SELECT D_E_L_E_T_ FROM inserted))
END 
GO


CREATE TRIGGER INSERE_STAGING_AREA_PEDIDO
ON Protheus12_Teste.dbo.SC6010 AFTER INSERT
AS
BEGIN
	DECLARE @C6_NUM VARCHAR(6)
	SELECT @C6_NUM = C6_NUM FROM inserted
	--IF (SELECT COUNT(*) FROM  Protheus12_Teste.dbo.SC6010 WHERE C6_NUM  = @C6_NUM AND C6_PRODUTO = (SELECT C6_PRODUTO FROM inserted)) = 0
		INSERT INTO DATA_WAREHOUSE.dbo.SA_PEDIDO(C5_FECENT, C5_NUM, C5_VEND1, C5_CLIENT, C5_LOJAENT, C5_FILIAL, C5_NOTA, C5_TIPO, C6_PRODUTO, C6_DESCRI, C6_QTDVEN, C6_NUM, C6_VALOR, C6_QTDREAL, C6_FILIAL, C6_SEGUM, C6_TES) 
		SELECT C5_FECENT, C5_NUM, C5_VEND1, C5_CLIENT, C5_LOJAENT, C5_FILIAL, C5_NOTA, C5_TIPO, C6_PRODUTO, C6_DESCRI, C6_QTDVEN, C6_NUM, C6_VALOR, C6_QTDREAL, C6_FILIAL, C6_SEGUM, C6_TES
			FROM Protheus12_Teste.dbo.SC5010 PED
			INNER JOIN Protheus12_Teste.dbo.SC6010 PROD ON  PED.C5_NUM = PROD.C6_NUM 
			WHERE C6_NUM = @C6_NUM AND C6_PRODUTO = (SELECT C6_PRODUTO FROM inserted) 
END
GO



CREATE TRIGGER INSERE_DATA_MART_VENDA
ON DATA_WAREHOUSE.dbo.SA_PEDIDO AFTER INSERT
AS 
BEGIN
	
	IF (SELECT COUNT(*) FROM DATA_WAREHOUSE.dbo.DATA_MART_VENDAS WHERE C5_NUM  = (SELECT C5_NUM FROM inserted) AND C6_PRODUTO = (SELECT C6_PRODUTO FROM inserted)) = 0
		INSERT INTO DATA_WAREHOUSE.dbo.DATA_MART_VENDAS(C5_FECENT, C5_NUM, C5_VEND1, C5_CLIENT, C5_LOJAENT, C5_FILIAL, C5_TIPO, C6_PRODUTO, C6_DESCRI, C6_QTDVEN, C6_NUM, C6_VALOR, C6_QTDREAL, C6_FILIAL, C6_SEGUM, C6_TES, B1_COD_PK, A3_COD_PK, DA6_COD_PK, DA7_COD_PK, F4_COD_PK)
		SELECT C5_FECENT, C5_NUM, C5_VEND1, C5_CLIENT, C5_LOJAENT, C5_FILIAL, C5_TIPO, C6_PRODUTO, C6_DESCRI, C6_QTDVEN, C6_NUM, C6_VALOR, C6_QTDREAL, C6_FILIAL, C6_SEGUM, C6_TES, TABPROD.B1_COD_PK, VEND.A3_COD_PK, ROTA.DA6_COD_PK, CID.DA7_COD_PK, TES.F4_COD_PK
			FROM SA_PEDIDO AS PEDIDO
			INNER JOIN SB1010 TABPROD ON TABPROD.B1_COD = PEDIDO.C6_PRODUTO
			INNER JOIN SA3010 VEND ON VEND.A3_COD = PEDIDO.C5_VEND1
			INNER JOIN DA7010 CID ON CID.DA7_CLIENT = PEDIDO.C5_CLIENT AND CID.DA7_LOJA = PEDIDO.C5_LOJAENT
			INNER JOIN DA6010 ROTA ON ROTA.DA6_ROTA = CID.DA7_ROTA
			INNER JOIN SF4010 TES ON TES.F4_CODIGO = PEDIDO.C6_TES
			WHERE PEDIDO.C5_NUM  = (SELECT C5_NUM FROM inserted) AND C6_PRODUTO = (SELECT C6_PRODUTO FROM inserted) 
END
GO



SELECT * FROM SA_PEDIDO

SELECT * FROM DATA_MART_VENDAS


ALTER TRIGGER INSERE_STAGING_AREA_FATURAMENTO
ON Protheus12_Teste.dbo.SD2010 AFTER INSERT
AS
BEGIN
		--IF (SELECT COUNT(*) FROM  Protheus12_Teste.dbo.SD2010 WHERE D2_DOC = (SELECT D2_DOC FROM inserted) AND D2_COD = (SELECT D2_COD FROM inserted)) = 0
		INSERT INTO DATA_WAREHOUSE.dbo.SA_FATURAMENTO(D2_SERIE, D2_DOC, D2_EMISSAO, D2_FILIAL, D2_COD, D2_QUANT, D2_PRCVEN, D2_TOTAL, D2_TES, D2_CLIENTE, D2_LOJA, F2_CLIENTE, F2_LOJA, F2_TIPO, F2_FILIAL, F2_DOC,F2_SERIE, F2_VEND1) 
		SELECT D2_SERIE, D2_DOC, D2_EMISSAO, D2_FILIAL, D2_COD, D2_QUANT, D2_PRCVEN, D2_TOTAL, D2_TES, D2_CLIENTE, D2_LOJA, F2_CLIENTE, F2_LOJA, F2_TIPO, F2_FILIAL, F2_DOC,F2_SERIE, F2_VEND1
			FROM Protheus12_Teste.dbo.SD2010 ITEM
			INNER JOIN Protheus12_Teste.dbo.SF2010 NOTA ON  NOTA.F2_CLIENTE = ITEM.D2_CLIENTE AND NOTA.F2_LOJA = ITEM.D2_LOJA 
														AND NOTA.F2_FILIAL = ITEM.D2_FILIAL AND NOTA.F2_DOC = ITEM.D2_DOC 
														AND NOTA.F2_SERIE = ITEM.D2_SERIE AND NOTA.D_E_L_E_T_ = '' 
			WHERE ITEM.D2_DOC = (SELECT D2_DOC FROM inserted) AND ITEM.D2_COD = (SELECT D2_COD FROM inserted) 
			  AND ITEM.D2_CLIENTE = (SELECT D2_CLIENTE FROM inserted) AND ITEM.D2_CLIENTE = (SELECT D2_CLIENTE FROM inserted) AND D2_LOJA = (SELECT D2_LOJA FROM inserted) AND ITEM.D2_SERIE = (SELECT D2_SERIE FROM inserted)
END
GO

SELECT * FROM DATA_MART_FATURAMENTO

SELECT * FROM SA_FATURAMENTO

select * from Protheus12_Teste.dbo.SD2010
WHERE D2_EMISSAO >= '20181112'


ALTER TRIGGER INSERE_DATA_MART_FATURAMENTO
ON DATA_WAREHOUSE.dbo.SA_FATURAMENTO AFTER INSERT
AS 
BEGIN
	
	IF (SELECT COUNT(*) FROM DATA_WAREHOUSE.dbo.DATA_MART_FATURAMENTO WHERE F2_DOC = (SELECT F2_DOC FROM inserted) AND D2_COD = (SELECT D2_COD FROM inserted)) = 0
		INSERT INTO DATA_MART_FATURAMENTO(D2_SERIE, D2_DOC, D2_EMISSAO, D2_FILIAL,	D2_COD,	D2_QUANT, D2_PRCVEN, D2_TOTAL, D2_TES, D2_CLIENTE, D2_LOJA, F2_CLIENTE, F2_LOJA, F2_TIPO, F2_FILIAL, F2_DOC,F2_SERIE, F2_VEND1, B1_COD_PK, A3_COD_PK, DA6_COD_PK, DA7_COD_PK, F4_COD_PK)
		SELECT D2_SERIE, D2_DOC, D2_EMISSAO, D2_FILIAL, D2_COD, D2_QUANT, D2_PRCVEN, D2_TOTAL, D2_TES, D2_CLIENTE, D2_LOJA, F2_CLIENTE, F2_LOJA, F2_TIPO, F2_FILIAL, F2_DOC,F2_SERIE, F2_VEND1, B1_COD_PK, A3_COD_PK, DA6_COD_PK, DA7_COD_PK, F4_COD_PK
			FROM SA_FATURAMENTO FAT 
			INNER JOIN DA7010 CID ON  CID.DA7_CLIENT = FAT.D2_CLIENTE AND CID.DA7_LOJA = FAT.D2_LOJA 
			INNER JOIN DA6010 ROTA ON ROTA.DA6_ROTA = CID.DA7_ROTA
			INNER JOIN SF4010 TES ON TES.F4_CODIGO = FAT.D2_TES 
			INNER JOIN SA3010 VEND ON VEND.A3_COD = FAT.F2_VEND1 
			INNER JOIN SB1010 TABPROD ON TABPROD.B1_COD = FAT.D2_COD 
			WHERE D2_DOC = (SELECT D2_DOC FROM inserted) AND D2_COD = (SELECT D2_COD FROM inserted)
END
GO