CREATE PROCEDURE INSERE_DADOS_SB1010
AS
BEGIN
	INSERT INTO SB1010(B1_COD,B1_DESC, B1_PESO, B1_FILIAL, D_E_L_E_T_)
	SELECT DISTINCT B1_COD, B1_DESC, B1_PESO, B1_FILIAL, D_E_L_E_T_
		FROM Protheus12.dbo.SB1010 TABPROD
		WHERE B1_COD BETWEEN '100' AND '800' AND TABPROD.D_E_L_E_T_ = ''
END
GO

CREATE PROCEDURE INSERE_DADOS_SA3010
AS
BEGIN
	INSERT INTO SA3010(A3_COD, A3_NOME, D_E_L_E_T_)
	SELECT DISTINCT A3_COD, A3_NOME, D_E_L_E_T_
		FROM Protheus12.dbo.SA3010 VEND
		WHERE VEND.D_E_L_E_T_ = ''
END
GO

CREATE PROCEDURE INSERE_DADOS_DA6010
AS
BEGIN
	INSERT INTO DA6010(DA6_REF, DA6_ROTA, D_E_L_E_T_)
	SELECT DISTINCT DA6_REF, DA6_ROTA, D_E_L_E_T_
		FROM Protheus12.dbo.DA6010 ROTA
		WHERE ROTA.D_E_L_E_T_ = ''
END
GO

CREATE PROCEDURE INSERE_DADOS_DA7010
AS
BEGIN
	INSERT INTO DA7010(DA7_CLIENT, DA7_LOJA, DA7_ROTA, D_E_L_E_T_)
	SELECT DISTINCT DA7_CLIENT, DA7_LOJA, DA7_ROTA, D_E_L_E_T_
		FROM Protheus12.dbo.DA7010 CID
		WHERE CID.D_E_L_E_T_ = ''
END
GO

CREATE PROCEDURE INSERE_DADOS_SF4010
AS
BEGIN
	INSERT INTO SF4010(F4_CODIGO, F4_DUPLIC, D_E_L_E_T_)
	SELECT DISTINCT F4_CODIGO, F4_DUPLIC, D_E_L_E_T_
		FROM Protheus12.dbo.SF4010 TES
		WHERE TES.D_E_L_E_T_ = ''
END
GO

CREATE PROCEDURE INSERE_DADOS_DATA_MART_VENDAS (@DATA_INICIAL VARCHAR(8))
AS
BEGIN
	INSERT INTO DATA_WAREHOUSE.dbo.DATA_MART_VENDAS(C5_FECENT, C5_NUM, C5_VEND1, C5_CLIENT, C5_LOJAENT, C5_FILIAL, C5_TIPO, C6_PRODUTO, C6_DESCRI, C6_QTDVEN, C6_NUM, C6_VALOR, C6_QTDREAL, C6_FILIAL, C6_SEGUM, C6_TES, B1_COD_PK, A3_COD_PK, DA6_COD_PK, DA7_COD_PK, F4_COD_PK)
	SELECT C5_FECENT, C5_NUM, C5_VEND1, C5_CLIENT, C5_LOJAENT, C5_FILIAL, C5_TIPO, C6_PRODUTO, C6_DESCRI, C6_QTDVEN, C6_NUM, C6_VALOR, C6_QTDREAL, C6_FILIAL, C6_SEGUM, C6_TES, TABPROD.B1_COD_PK, VEND.A3_COD_PK, ROTA.DA6_COD_PK, CID.DA7_COD_PK, TES.F4_COD_PK
		FROM Protheus12.dbo.SC5010 PED
		LEFT JOIN Protheus12.dbo.SC6010 PROD ON  PED.C5_NUM = PROD.C6_NUM 
		LEFT JOIN SB1010 TABPROD ON TABPROD.B1_COD = PROD.C6_PRODUTO
		INNER JOIN SA3010 VEND ON VEND.A3_COD = PED.C5_VEND1
		INNER JOIN DA7010 CID ON CID.DA7_CLIENT = PED.C5_CLIENT AND CID.DA7_LOJA = PED.C5_LOJAENT
		INNER JOIN DA6010 ROTA ON ROTA.DA6_ROTA = CID.DA7_ROTA
		LEFT JOIN SF4010 TES ON TES.F4_CODIGO = PROD.C6_TES
		WHERE PED.C5_FECENT >= @DATA_INICIAL
END
GO

CREATE PROCEDURE INSERE_DADOS_DATA_MART_FATURAMENTO (@DATA_INICIAL VARCHAR(8))
AS
BEGIN
	INSERT INTO DATA_MART_FATURAMENTO(D2_SERIE, D2_DOC, D2_EMISSAO, D2_FILIAL,	D2_COD,	D2_QUANT, D2_PRCVEN, D2_TOTAL, D2_TES, D2_CLIENTE, D2_LOJA, F2_CLIENTE, F2_LOJA, F2_TIPO, F2_FILIAL, F2_DOC,F2_SERIE, F2_VEND1, B1_COD_PK, A3_COD_PK, DA6_COD_PK, DA7_COD_PK, F4_COD_PK)
	SELECT D2_SERIE, D2_DOC, D2_EMISSAO, D2_FILIAL, D2_COD, D2_QUANT, D2_PRCVEN, D2_TOTAL, D2_TES, D2_CLIENTE, D2_LOJA, F2_CLIENTE, F2_LOJA, F2_TIPO, F2_FILIAL, F2_DOC,F2_SERIE, F2_VEND1, B1_COD_PK, A3_COD_PK, DA6_COD_PK, DA7_COD_PK, F4_COD_PK
		FROM Protheus12.dbo.SD2010 ITEM 
		INNER JOIN Protheus12.dbo.SF2010 NOTA ON NOTA.F2_CLIENTE = ITEM.D2_CLIENTE 
									 AND NOTA.F2_LOJA = ITEM.D2_LOJA 
									 AND NOTA.F2_FILIAL = 	ITEM.D2_FILIAL 
									 AND NOTA.F2_DOC = ITEM.D2_DOC 
									 AND NOTA.F2_SERIE = ITEM.D2_SERIE 
		INNER JOIN DA7010 CID ON  CID.DA7_CLIENT = ITEM.D2_CLIENTE AND CID.DA7_LOJA = ITEM.D2_LOJA 
		INNER JOIN DA6010 ROTA ON ROTA.DA6_ROTA = CID.DA7_ROTA
		INNER JOIN SF4010 TES ON TES.F4_CODIGO = ITEM.D2_TES 
		INNER JOIN SA3010 VEND ON VEND.A3_COD = NOTA.F2_VEND1 
		INNER JOIN SB1010 TABPROD ON TABPROD.B1_COD = ITEM.D2_COD 
		WHERE D2_EMISSAO >= @DATA_INICIAL 
END
GO

CREATE PROCEDURE CRIAR_DW (@DATA_INICIAL VARCHAR(8))
AS
BEGIN
	
	EXEC INSERE_DADOS_SB1010
	EXEC INSERE_DADOS_SA3010
	EXEC INSERE_DADOS_DA6010
	EXEC INSERE_DADOS_DA7010
	EXEC INSERE_DADOS_SF4010
	EXEC INSERE_DADOS_DATA_MART_VENDAS @DATA_INICIAL
	EXEC INSERE_DADOS_DATA_MART_FATURAMENTO @DATA_INICIAL
END
GO


CREATE PROCEDURE LIMPA_DADOS
AS
BEGIN
	DELETE FROM DATA_MART_VENDAS
	DELETE FROM DATA_MART_FATURAMENTO
	DELETE FROM SA_PEDIDO
	DELETE FROM SA_FATURAMENTO
	DELETE FROM DA7010
	DELETE FROM DA6010
	DELETE FROM SA3010
	DELETE FROM SB1010
	DELETE FROM SF4010
END
GO



EXEC CRIAR_DW '20181101' 

EXEC LIMPA_DADOS



